config/routes.rb
Rails.application.routes.draw do

  resources :appointments
  resources :addresses
  resources :forms
  devise_for :users, controllers: { registrations: 'registrations'}
  root 'pages#home'

  get 'dashboard', to: 'pages#dashboard'

end

app/models/address.rb
class Address < ActiveRecord::Base

	validates_presence_of :first_name
    #validates_presence_of :middle_name
    #validates_presence_of :last_name
    #validates_presence_of :drivers_license
    #validates_presence_of :date_of_birth
    #validates_presence_of :street_number
    #validates_presence_of :street_name
    #validates_presence_of :city
    #validates_presence_of :state
    #validates_presence_of :zip_code
    #validates_presence_of :submitted_on
    #validates_presence_of :user_id
    validates_presence_of :file

    belongs_to :user
    
    

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

	validates_presence_of :reason
	#validates_presence_of :slot
	validates_presence_of :appt

	belongs_to :user
	

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    validates_presence_of :name
    has_many :address
    has_many :appointment

    
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy ]
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  #before_action :index, only: [:current_user]

  
def upload
  uploaded_io = params[:address][:file]
  File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
    file.write(uploaded_io.read)
  end
end


  # GET /addresses
  # GET /addresses.json
  def index
    #@addresses = Address.all
    #@addresses = @user.Address.all
    #@addresses = Address.
    @user = current_user
    @address = @user.address
    @appointment = @user.appointment
      
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    #@address = Address.new(address_params)
    @address = current_user.address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Form was submitted successfully!' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Form was updated successfully!' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Form was deleted successfully!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:first_name, :file )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy ]
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    #@appointments = Appointment.all
    @user = current_user
    @address = @user.address
    @appointment = @user.appointment
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    #@appointment = Appointment.new(appointment_params)
    @appointment = current_user.appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was created successfully!' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was udapted successfully!' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was cancelled successfully!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:reason, :slot, :appt)
    end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def home
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, only: [:dashboard]

  def home
    if current_user 
      redirect_to dashboard_path
    end
  end


  def dashboard
  	@user = current_user
  	@address = @user.address
  	@appointment = @user.appointment
  end

end

app/controllers/registrations_controller.rb
# create a new file in the controllers folder

class RegistrationsController < Devise::RegistrationsController
	
	def sign_up_params
		params.require(:user).permit(:name, :email, :password)
	end

	def account_update_params
		params.require(:user).permit(:name, :email, :password, :current_password)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/addresses/_form.html.erb
<%= simple_form_for(@address) do |f| %>

  <div class="form-inputs">
    
    
    <%= f.label(:first_name, "Form ID") %>
    <%= f.select(:first_name, { 'DMV 14 - change of address' => "DMV 14", 'INF 1125 - request for registration record' => "INF 1125", 'SR 1 - traffic accident report' => "SR 1", 'REG 135 - bill of sale' => "REG 135", 'REG 138 - release of liability' => "REG 138", 'REG 227 - request for duplicate title' => "REG 227", 'REG 343 - request for title or registration' => "REG 343", 'REG 256 - statement of facts' => "REG 256", 'REG 17 - special interest license plate' => "REG 17", 'REG 156 - request for replacement items' => "REG 156", 'Other' => "Other"}, :required => true) %>

  </div>

  <br>


  <%= filepicker_js_include_tag %>
  <%= form_for @address do |f| %>
      <div>
        <%= f.label :file, "Select file:" %>
        <%= f.filepicker_field :file, :required => true %>

      </div>
    <br>
    
    <div class="form-actions">
    <%= f.button "submit form", class: 'btn btn-primary btn-lg'%>
    </div>
    
    <% end %>

<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/forms.html.erb
<h1>Submitted Forms</h1>

<table class="table">
  <thead>
    <tr>
      <th>Form 1</th>
      <th>Form 2</th>
      <th>Form 3</th>
      <th>Form 4</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><a class="btn btn-primary btn-lg" role="button" <%= link_to 'submit a new form', new_address_path %></td>
        <td><a class="btn btn-primary btn-lg" role="button" <%= link_to 'submit a new form', new_address_path %></td>
        <td><a class="btn btn-primary btn-lg" role="button" <%= link_to 'submit a new form', new_address_path %></td>
        <td><a class="btn btn-primary btn-lg" role="button" <%= link_to 'submit a new form', new_address_path %></td>
      </tr>
    <% end %>
  </tbody>
  <% end %>

</table>

app/views/addresses/index.html.erb
<div class="jumbotron">

<h1>Submitted Forms</h1>
<br>
<br>

<table class="table">
  <thead>
    <tr>
      <th>Form ID</th>
      <th>Submitted</th>
      <th>View Form</th>
      <th>Delete Form</th>
    </tr>
  </thead>

  <% if current_user %> 
  <tbody>
    <% @address.each do |address| %>
      <tr>
        <td><%= address.first_name %></td>
        <td><%= time_ago_in_words(address.created_at) %> ago</td>
        <td><%= link_to 'view', address.file %></td>
        <td><%= link_to 'delete', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  <% end %>
</table>

<br>
<% if current_user %> 
<a class="btn btn-primary btn-lg" role="button" <%= link_to 'submit a new form', new_address_path %>
<% end %> 

</div>

app/views/addresses/new.html.erb
<div class="jumbotron">

<h1>Submit a Form</h1>
<br>
<h5 style="color:#999999">To submit a new form, select the form ID, select a file, and press 'submit form'.</h5>
<br>
<%= render 'form' %>

</div>

app/views/addresses/show.html.erb
<div class="jumbotron">

<p id="notice"><%= notice %></p>

<p>
  <strong>form ID:</strong>
  <%= @address.first_name %>
</p>

<p>
  <strong>view:</strong>
  <%= link_to 'link', @address.file %>
  <%= filepicker_js_include_tag %>
</p>


<%= link_to 'return to forms list', addresses_path %> | <%= link_to 'return to dashboard', dashboard_path %>

</div>

app/views/appointments/_form.html.erb
<%= simple_form_for(@appointment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.label(:reason, "Reason for visit: ") %>
    <%= f.select(:reason, { 
      'Permit Test' => "Permit Test", 
      'Drivers Test' => "Drivers Test", 
      'License Renewal' => "License Renewal", 
      'Vehicle Registration' => "Vehicle Registration", 
      'Title Transfer' => "Title Transfer", 
      'Pay Fees' => "Pay Fees", 
      'Other' => "Other"
      }, :required => true) %>
    <br>
    <br>
    <%= f.label(:appt, "Date/Time: ") %>
    <%= f.select(:appt, { 
      'Friday February 19th at 09:00am' => "Friday February 19th at 09:00am",
      'Friday February 19th at 10:00am' => "Friday February 19th at 10:00am",
      'Friday February 19th at 02:00pm' => "Friday February 19th at 02:00pm",
      'Monday February 22nd at 09:00am' =>"Monday February 22nd at 09:00am",
      'Monday February 22nd at 10:00am' => "Monday February 22nd at 10:00am",
      'Monday February 22nd at 02:00pm' => "Monday February 22nd at 02:00pm",
      'Tuesday February 23rd at 09:00am' => "Tuesday February 23rd at 09:00am",
      'Tuesday February 23rd at 10:00am' => "Tuesday February 23rd at 10:00am",
      'Tuesday February 23rd at 02:00pm' => "Tuesday February 23rd at 02:00pm",
      'Wednesday February 24th at 09:00am' => "Wednesday February 24th at 09:00am",
      'Wednesday February 24th at 10:00am' => "Wednesday February 24th at 10:00am",
      'Wednesday February 24th at 02:00pm' => "Wednesday February 24th at 02:00pm",
      'Thursday February 25th at 09:00am' => "Thursday February 25th at 09:00am",
      'Thursday February 25th at 10:00am' => "Thursday February 25th at 10:00am",
      'Thursday February 25th at 02:00pm' => "Thursday February 25th at 02:00pm"
      }, :required => true) %>



  </div>



  <br>

  <div class="form-actions">
  	<%= f.submit 'schedule appointment', class: 'btn btn-primary btn-lg'%>
  </div>



  

  <% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<div class="jumbotron">

<h1>Appointments</h1>
<br>
<br>

<table class ="table">
  <thead>
    <tr>
      <th>Reason</th>
      <th>Date/Time</th>
      <th>View Appointment</th>
      <th>Cancel Appointment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointment.each do |appointment| %>
      <tr>
        <td><%= appointment.reason %></td>
        <td><%= appointment.appt %></td>
        <td><%= link_to 'view', appointment %></td>
        <td><%= link_to 'cancel', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user %> 
<a class="btn btn-primary btn-lg" role="button" <%= link_to 'schedule new appointment', new_appointment_path %>
<% end %>

</div>

app/views/appointments/new.html.erb
<div class="jumbotron">

<h1>New Appointment</h1>
<br>
<h5 style="color:#999999">To schedule a new appointment, select a reason, select a time slot, and press 'schedule appointment'.</h5>
<br>

<%= render 'form' %>

</div>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reason:</strong>
  <%= @appointment.reason %>
</p>

<p>
  <strong>Date/Time:</strong>
  <%= @appointment.appt %>
</p>

<%= link_to 'return to appointments list', appointments_path %> | <%= link_to 'return to dashboard', dashboard_path %>

app/views/forms/home.html.erb
<h1>Forms#home</h1>
<p>Find me in app/views/forms/home.html.erb</p>

app/views/forms/index.html.erb
<div class="jumbotron">

<h1>Available Forms</h1>
<br>
<br>

<table class ="table">
  <thead>
    <tr>
      <th>Form ID</th>
      <th>Form Name</th>
      <th>Download Form</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>DMV 14</td>
        <td>change of address</td>
        <td><a href="https://www.dmv.ca.gov/portal/wcm/connect/d7d1a212-f8df-45b1-a9ee-c09454a5b423/dmv14.pdf?MOD=AJPERES">download</a></td>
      </tr>
      <tr>
        <td>INF 1125</td>
        <td>request for registration record</td>
        <td><a href="https://www.dmv.ca.gov/portal/wcm/connect/9dbbabee-26d3-4490-80db-b7e161a3e6b8/inf1125.pdf?MOD=AJPERES">download</a></td>
      </tr>
      <tr>
        <td>SR 1</td>
        <td>traffic accident report</td>
        <td><a href="https://www.dmv.ca.gov/portal/wcm/connect/18eb2422-e5ea-4b88-9322-c0f8330862f9/sr1.pdf?MOD=AJPERES">download</a></td></td>
      </tr>
      <tr>
        <td>REG 135</td>
        <td>bill of sale</td>
        <td><a href="https://www.dmv.ca.gov/portal/wcm/connect/b04d574c-a959-4160-953b-faf62a66cd3a/reg135.pdf?MOD=AJPERES">download</a></td></td>
      </tr>
      <tr>
        <td>REG 138</td>
        <td>release of liability</td>
        <td><a href="https://www.dmv.ca.gov/portal/wcm/connect/503960c5-6d95-4e5f-b123-3f584e16c012/reg138.pdf?MOD=AJPERES">download</a></td></td>
      </tr>

      <tr>
        <td>REG 227</td>
        <td>request for duplicate title</td>
        <td><a href="https://www.dmv.ca.gov/portal/wcm/connect/7885d40d-4d2e-4fc0-b100-3ef8fe562bd7/reg227.pdf?MOD=AJPERES">download</a></td>
      </tr>
      <tr>
        <td>REG 343</td>
        <td>request for title or registration</td>
        <td><a href="https://www.dmv.ca.gov/portal/wcm/connect/8c4e5fdb-a44e-44f6-853b-eabd471afdaa/reg343.pdf?MOD=AJPERES">download</a></td>
      </tr>
      <tr>
        <td>REG 256</td>
        <td>statement of facts</td>
        <td><a href="https://www.dmv.ca.gov/portal/wcm/connect/5a40cbcc-a9a9-4a42-ac43-a8564fa552c0/reg256.pdf?MOD=AJPERES">download</a></td></td>
      </tr>
      <tr>
        <td>REG 17</td>
        <td>special interest license plate</td>
        <td><a href="https://www.dmv.ca.gov/portal/wcm/connect/6d97bdef-c5b1-46ee-a558-28ab938e4ec3/reg17.pdf?MOD=AJPERES">download</a></td></td>
      </tr>
      <tr>
        <td>REG 156</td>
        <td>request for replacement items</td>
        <td><a href="https://www.dmv.ca.gov/portal/wcm/connect/78848945-2d42-4903-a38b-329805062c7e/reg156.pdf?MOD=AJPERES">download</a></td></td>
      </tr>

  </tbody>
</table>

<br>
<% if current_user %> 
<a class="btn btn-primary btn-lg" role="button" <%= link_to 'submit a new form', new_address_path %>
<% end %> 



</div>

app/views/layouts/_footer.html.erb
<nav class="footer navbar-fixed-bottom">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->

      <a class="navbar-brand navbar-right" style="color:#777777;">created by Cory Malstrom</a>
    
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <a class="navbar-brand" style="color:#428DC8; font-weight:bold;"><i class="fa fa-car" style="color:#000000"></i> DMVsync™</a>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <% if current_user %>
           <li><%= link_to 'dashboard', dashboard_path %> </li>

           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">appointments <span class="caret"></span></a>
              <ul class="dropdown-menu">

                <li><%= link_to 'schedule new appointment', new_appointment_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'view your appointments', appointments_path %></li>
              </ul>
          </li>

           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">forms <span class="caret"></span></a>
              <ul class="dropdown-menu">

                <li><%= link_to 'submit new form', new_address_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'view submitted forms', addresses_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'download a form', forms_path %></li>

              </ul>
          </li>

          <!-- <li><a href="pages#registrations">view your registrations</a></li> -->
          

        <% else %>
        
        <% end %>

      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        
        <% if current_user %>
           <li><%= link_to 'settings', edit_user_registration_path %> </li>          
          <li><%= link_to 'logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'login', new_user_session_path %></li>
          <li><%= link_to 'register', new_user_registration_path %></li>
        <% end %>


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DMVsync</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>
	<%= render 'layouts/footer' %>

	<% flash.each do |type, message|  %>
		<div class="alert alert-info fade-in">
			<button class="close" data-dismiss="alert">X</button>
			<%= message %>
		</div>
	<% end %>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/appointments.html.erb
<h1>This should be the APPOINTMENTS page</h1>

app/views/pages/dashboard.html.erb
<div class="jumbotron">
<h1>Dashboard</h1>
<br>

<div class="row">
	

	<!-- addresses(forms) -->
	<div class="col-md-5">
	<h2 style="color:#428DC8;">Forms</h2>
	<table class="table">
	    <thead>
			<tr>
				<th>Form ID</th>
				<th>Submitted</th>
				<th>View Form</th>
      			<th>Cancel Form</th>
			</tr>
	    </thead>

		<tbody>
			<% @address.each do |address|  %>
				<tr>
					<td><%= address.first_name %></td>
					<td><%= time_ago_in_words(address.created_at) %> ago</td>
					<td><%= link_to 'view', address.file %></td>
					<td><%= link_to "cancel", address_path(address), method: :delete %></td>
				</tr>
			<% end %>

		</tbody>
	</table>
	<a class="btn btn-primary btn-md" role="button" <%= link_to 'submit a new form', new_address_path %>
	</div>

	<!-- appointments -->
	<div class="col-md-5">
	<h2 style="color:#428DC8;">Appointments</h2>
	<table class="table">
		<thead>
			<tr>
				<th>Reason</th>
				<th>Date/Time</th>
			</tr>
		</thead>

		<tbody>
			<% @appointment.each do |appointment| %>
				<tr>
					<td><%= appointment.reason %></td>
					<td><%= appointment.slot.to_s %></td>
					<td><%= link_to 'view', appointment %></td>
					<td><%= link_to "cancel", appointment_path(appointment), method: :delete %></td>

				 </tr>
			<% end %>
		</tbody>
		</table>
		<a class="btn btn-primary btn-md" role="button" <%= link_to 'schedule new appointment', new_appointment_path %>
		</div>

		
</div>

app/views/pages/forms.html.erb
<h1>This should be the FORMS page</h1>

app/views/pages/home.html.erb
<div class="jumbotron">

  <% if current_user %>

  <h1 style="color:#000000">
    <span style="color:#428DC8">Welcome Back!</span>
  </h1>
  <p>Select an option from the navigation bar above. You can view your appointments, schedule a new appointment, view your submitted forms, submit a new form, or download a form.</p>
  <a class="btn btn-primary btn-lg" role="button" <%= link_to 'logout', destroy_user_session_path, method: :delete %>

  <% else %>
  <h2>
  	<span style="color:#000000">Welcome to </span>
  	<span style="color:#428DC8">DMVsync!</span>
  </h2>
  <br>
  <p>The easiest way to view your current vehicle registration, submit a form to the DMV, and schedule an appointment.</p>
  <p>
  <a class="btn btn-primary btn-lg" role="button" <%= link_to 'login', new_user_session_path %>
  <a class="btn btn-primary btn-lg" role="button" <%= link_to 'register', new_user_registration_path %>
  </p>
  <% end %>

</div>

app/views/pages/registrations.html.erb
<h1>This should be the REGISTRATION page</h1>

app/views/welcome/index.html.erb
<div class="jumbotron">

  <% if current_user %>

  <h1 style="color:#000000">
    <span style="color:#428DC8">Welcome Back!</span>
  </h1>
  <p>Select an option from the navigation bar above. You can view your appointments, schedule a new appointment, view your submitted forms, submit a new form, or download a form.</p>
  <a class="btn btn-primary btn-lg" role="button" <%= link_to 'logout', destroy_user_session_path, method: :delete %>

  <% else %>
  <h1 style="color:#000000">
  	<span style="color:#000000">Welcome to </span>
  	<span style="color:#428DC8">DMVsync!</span>
  </h1>
  <p>The easiest way to view your current vehicle registration, submit a form to the DMV, and schedule an appointment.</p>
  <p>
  <a class="btn btn-primary btn-lg" role="button" <%= link_to 'login', new_user_session_path %>
  <a class="btn btn-primary btn-lg" role="button" <%= link_to 'register', new_user_registration_path %>
  </p>
  <% end %>

</div>